In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.randn(1,3,9,9)
y = F.interpolate(x,size=3,mode='bilinear')
y.shape

torch.Size([1, 3, 3, 3])

In [22]:
a = torch.randn(1,3,2,2)
model = nn.ConvTranspose2d(in_channels=3,out_channels=1,kernel_size=6,stride=2,padding=2)
print(model.weight.shape)

torch.Size([3, 1, 6, 6])


In [24]:
model2 = nn.Conv2d(in_channels=1,out_channels=3,stride=1,kernel_size=1,padding=0)
print(model2.weight.shape)

torch.Size([3, 1, 1, 1])


In [25]:
model = nn.ConvTranspose2d(in_channels=3,out_channels=16,kernel_size=4*2,stride=4,padding=4//2)
x = torch.randn(1,3,48,48)
print(model(x).shape)

torch.Size([1, 16, 192, 192])


In [13]:
model = nn.Conv2d(in_channels=3,out_channels=3,kernel_size=3,stride=1,padding=1,dilation=1)
x=torch.randn(1,3,48,48)
print(model(x).shape)

torch.Size([1, 3, 48, 48])


In [7]:
x = torch.randn(1,64,4,4)
y = F.softmax(x,dim=1)
y[0,0,:,:]

tensor([[0.0324, 0.0023, 0.0108, 0.0072],
        [0.0022, 0.0063, 0.0203, 0.0887],
        [0.0059, 0.0009, 0.0041, 0.0295],
        [0.0153, 0.0057, 0.0821, 0.0229]])

In [19]:
a = torch.randn(1,6,1,2)
print(a)
b = F.channel_shuffle(a,2)
print(b)

tensor([[[[ 0.7692,  0.8337]],

         [[-0.7597,  1.2409]],

         [[-0.2799, -0.4478]],

         [[-1.6583,  0.8637]],

         [[-0.2476, -1.6542]],

         [[-1.2074,  1.1537]]]])
tensor([[[[ 0.7692,  0.8337]],

         [[-1.6583,  0.8637]],

         [[-0.7597,  1.2409]],

         [[-0.2476, -1.6542]],

         [[-0.2799, -0.4478]],

         [[-1.2074,  1.1537]]]])


In [27]:
x = torch.randn(1,4,4,9)
y = F.pad(x, (0,1), mode="constant", value=1)
y.shape

torch.Size([1, 4, 4, 10])

In [31]:
a = torch.randn(1,12,1,1)
a

tensor([[[[ 1.9643]],

         [[ 0.6037]],

         [[-0.1409]],

         [[-0.9078]],

         [[-0.2933]],

         [[-1.6091]],

         [[-0.9777]],

         [[ 0.4756]],

         [[ 1.0614]],

         [[-0.6278]],

         [[ 0.5207]],

         [[ 0.0545]]]])

In [32]:
a.reshape(1,4,3,1,1)

tensor([[[[[ 1.9643]],

          [[ 0.6037]],

          [[-0.1409]]],


         [[[-0.9078]],

          [[-0.2933]],

          [[-1.6091]]],


         [[[-0.9777]],

          [[ 0.4756]],

          [[ 1.0614]]],


         [[[-0.6278]],

          [[ 0.5207]],

          [[ 0.0545]]]]])