In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.randn(1,3,9,9)
y = F.interpolate(x,size=3,mode='bilinear')
y.shape

torch.Size([1, 3, 3, 3])

In [22]:
a = torch.randn(1,3,2,2)
model = nn.ConvTranspose2d(in_channels=3,out_channels=1,kernel_size=6,stride=2,padding=2)
print(model.weight.shape)

torch.Size([3, 1, 6, 6])


In [24]:
model2 = nn.Conv2d(in_channels=1,out_channels=3,stride=1,kernel_size=1,padding=0)
print(model2.weight.shape)

torch.Size([3, 1, 1, 1])


In [25]:
model = nn.ConvTranspose2d(in_channels=3,out_channels=16,kernel_size=4*2,stride=4,padding=4//2)
x = torch.randn(1,3,48,48)
print(model(x).shape)

torch.Size([1, 16, 192, 192])


In [36]:
model = nn.Conv2d(in_channels=3,out_channels=3,kernel_size=3,stride=1,padding=2,dilation=2)
x=torch.randn(1,3,48,48)
print(model(x).shape)

torch.Size([1, 3, 46, 46])


In [7]:
x = torch.randn(1,64,4,4)
y = F.softmax(x,dim=1)
y[0,0,:,:]

tensor([[0.0324, 0.0023, 0.0108, 0.0072],
        [0.0022, 0.0063, 0.0203, 0.0887],
        [0.0059, 0.0009, 0.0041, 0.0295],
        [0.0153, 0.0057, 0.0821, 0.0229]])

In [19]:
a = torch.randn(1,6,1,2)
print(a)
b = F.channel_shuffle(a,2)
print(b)

tensor([[[[ 0.7692,  0.8337]],

         [[-0.7597,  1.2409]],

         [[-0.2799, -0.4478]],

         [[-1.6583,  0.8637]],

         [[-0.2476, -1.6542]],

         [[-1.2074,  1.1537]]]])
tensor([[[[ 0.7692,  0.8337]],

         [[-1.6583,  0.8637]],

         [[-0.7597,  1.2409]],

         [[-0.2476, -1.6542]],

         [[-0.2799, -0.4478]],

         [[-1.2074,  1.1537]]]])


In [27]:
x = torch.randn(1,4,4,9)
y = F.pad(x, (0,1), mode="constant", value=1)
y.shape

torch.Size([1, 4, 4, 10])

In [37]:
a = torch.randn(1,12,1,1).float16()
a

AttributeError: 'Tensor' object has no attribute 'float16'

In [38]:
a = torch.randn(1,2,4)
b = torch.topk(a,k=2,dim=2)
print(a)
print(b)

tensor([[[-0.0074, -1.7223,  1.5647, -0.0307],
         [ 0.2083,  1.2695, -0.5241, -1.5483]]])
torch.return_types.topk(
values=tensor([[[ 1.5647, -0.0074],
         [ 1.2695,  0.2083]]]),
indices=tensor([[[2, 0],
         [1, 0]]]))


In [44]:
a = torch.randn(1,3*16,12,12)
F.pixel_shuffle(a,upscale_factor=4).shape

torch.Size([1, 3, 48, 48])

In [52]:
model = nn.Conv2d(in_channels=6,out_channels=6,kernel_size=1,groups=3)
a=torch.randn(1,6,2,2)
model.weight.shape


torch.Size([6, 2, 1, 1])

In [56]:

w = torch.tensor([[[[1]],[[1]]],
                  [[[2]],[[2]]],
                  [[[3]],[[3]]],
                  [[[4]],[[4]]],
                  [[[5]],[[5]]],
                  [[[6]],[[6]]]]).float()
x = torch.randn(1,6,2,2)
F.conv2d(x,weight=w,groups=3)

tensor([[[[ 2.1513,  0.7702],
          [ 0.2443,  0.0759]],

         [[ 4.3026,  1.5404],
          [ 0.4887,  0.1517]],

         [[ 6.8957, -2.7130],
          [-1.1354, -3.7653]],

         [[ 9.1942, -3.6173],
          [-1.5139, -5.0204]],

         [[ 6.4053,  5.6710],
          [ 1.2167, -5.3678]],

         [[ 7.6864,  6.8052],
          [ 1.4600, -6.4413]]]])

In [57]:
x

tensor([[[[ 1.0122, -0.2299],
          [-0.4805,  0.3924]],

         [[ 1.1391,  1.0001],
          [ 0.7249, -0.3166]],

         [[ 1.0646, -0.1734],
          [-0.0793, -0.3979]],

         [[ 1.2340, -0.7309],
          [-0.2992, -0.8571]],

         [[ 0.6578,  0.5802],
          [-0.9655, -0.3521]],

         [[ 0.6233,  0.5540],
          [ 1.2088, -0.7214]]]])