In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange


In [47]:
x = torch.randn(1,3,6,6)
#print(x)
b,c,h,w = x.shape
n_w,n_h=2,2

y = F.unfold(x,kernel_size=(h//n_h, w//n_w),stride=(h//n_h, w//n_w))
y = y.transpose(1,2).reshape(1,n_w*n_h,c,(h*w)//(n_h*n_w)).transpose(2,3)
print(y.shape)
# z = rearrange(x, "n (j h) (i w) c -> n (j i) h w c", j=n_h, i=n_w)
# print(z.shape)

torch.Size([1, 4, 9, 3])


In [55]:
y

-0.28976666666666673

In [54]:
torch.mean(y,dim=2)

tensor([[[-0.2898, -0.1277, -0.1337],
         [-0.3539, -0.3940, -0.2608],
         [-0.4693, -0.2980,  0.2554],
         [ 0.3358,  0.0323,  0.2262]]])

In [56]:
y.mean(dim=2)

tensor([[[-0.2898, -0.1277, -0.1337],
         [-0.3539, -0.3940, -0.2608],
         [-0.4693, -0.2980,  0.2554],
         [ 0.3358,  0.0323,  0.2262]]])

In [67]:
a = torch.randn(1,6,6)
b = torch.randn(1,6,2,3)
print(a)
print(torch.topk(a,k=3,dim=2))
index = torch.topk(a,k=3,dim=2).indices

tensor([[[-0.5991,  0.7648, -0.5720,  2.0479, -1.6885,  0.1651],
         [ 0.6715,  0.8674, -1.2236,  0.0321,  1.2687, -1.7453],
         [ 0.4149,  1.0493,  1.3574, -1.3188, -0.9084, -0.9562],
         [ 1.5739,  0.4355,  1.2332,  0.6527,  0.0653, -2.0187],
         [ 2.2451, -0.4708,  1.0639, -1.2613,  0.9120,  1.8629],
         [-0.6142, -1.0106, -0.5500,  0.5309,  0.7194, -0.9959]]])
torch.return_types.topk(
values=tensor([[[ 2.0479,  0.7648,  0.1651],
         [ 1.2687,  0.8674,  0.6715],
         [ 1.3574,  1.0493,  0.4149],
         [ 1.5739,  1.2332,  0.6527],
         [ 2.2451,  1.8629,  1.0639],
         [ 0.7194,  0.5309, -0.5500]]]),
indices=tensor([[[3, 1, 5],
         [4, 1, 0],
         [2, 1, 0],
         [0, 2, 3],
         [0, 5, 2],
         [4, 3, 2]]]))


In [68]:
print(b) #(1,6,2,3)

tensor([[[[ 1.1312, -2.0286, -1.1819],
          [ 0.9590, -0.1457, -0.7932]],

         [[ 0.8317,  0.0247, -0.8975],
          [ 2.2067,  1.8521,  1.0173]],

         [[ 0.7001, -0.8354,  0.3814],
          [ 0.4911,  1.3858,  0.1873]],

         [[ 1.5381, -0.8013, -0.5527],
          [ 1.2489,  0.2170, -0.8703]],

         [[-0.2474, -0.4907,  0.0487],
          [-1.3639,  0.3985, -0.0991]],

         [[-2.2651,  0.0506, -0.0028],
          [-0.5266,  1.2990, -0.6306]]]])


In [71]:
inner_list = []
for i in index[0]:
    inner = b[:, i ,:,:].reshape(1,1,6,3)
    inner_list.append(inner)
print(torch.cat(inner_list,dim=1))


# c = b[:,[1,5,0],:,:].reshape(1,1,6,3)
# d = b[:,[0,1,4],:,:].reshape(1,1,6,3)
# out = torch.cat([c,d],dim=1)
# print(out)
# print(c.shape)

tensor([[[[ 1.5381, -0.8013, -0.5527],
          [ 1.2489,  0.2170, -0.8703],
          [ 0.8317,  0.0247, -0.8975],
          [ 2.2067,  1.8521,  1.0173],
          [-2.2651,  0.0506, -0.0028],
          [-0.5266,  1.2990, -0.6306]],

         [[-0.2474, -0.4907,  0.0487],
          [-1.3639,  0.3985, -0.0991],
          [ 0.8317,  0.0247, -0.8975],
          [ 2.2067,  1.8521,  1.0173],
          [ 1.1312, -2.0286, -1.1819],
          [ 0.9590, -0.1457, -0.7932]],

         [[ 0.7001, -0.8354,  0.3814],
          [ 0.4911,  1.3858,  0.1873],
          [ 0.8317,  0.0247, -0.8975],
          [ 2.2067,  1.8521,  1.0173],
          [ 1.1312, -2.0286, -1.1819],
          [ 0.9590, -0.1457, -0.7932]],

         [[ 1.1312, -2.0286, -1.1819],
          [ 0.9590, -0.1457, -0.7932],
          [ 0.7001, -0.8354,  0.3814],
          [ 0.4911,  1.3858,  0.1873],
          [ 1.5381, -0.8013, -0.5527],
          [ 1.2489,  0.2170, -0.8703]],

         [[ 1.1312, -2.0286, -1.1819],
          [ 0.959

In [64]:
c.reshape(1,1,6,3)

tensor([[[[ 0.9395,  1.0641,  0.3440],
          [ 0.3677,  0.2351, -1.2597],
          [ 0.3056,  0.0020,  0.2651],
          [-0.0344, -1.7146,  1.1489],
          [-1.3257,  1.2709, -0.3341],
          [-1.2552, -0.2155,  1.1634]]]])

In [73]:
a = torch.randn(2,3,4)
for i in a[:,]:
    print(i)

tensor([[-0.1287, -1.0688,  0.9372,  0.0701],
        [ 0.6310, -0.4409,  0.9477, -1.9170],
        [-1.5138,  0.7465, -0.4902,  1.5684]])
tensor([[ 0.1882, -0.5668,  0.8773,  0.4107],
        [-0.6995, -1.0611, -0.2847,  0.8241],
        [-0.6709,  2.2328, -1.3086,  1.0862]])


In [103]:
a = torch.randn(2, 6, 4)
b = torch.randn(2, 4, 4)
print(torch.matmul(a, b))  # 进行张量乘法

tensor([[[ 6.2814e-01,  3.5876e-02, -5.6434e-01,  1.1323e+00],
         [-1.4727e+00, -2.5746e-01,  6.5216e-01, -1.2715e+00],
         [ 1.9681e+00,  5.7480e+00, -3.5879e-01, -1.2408e+00],
         [-1.4625e+00, -1.2430e+00,  1.1019e+00,  3.9845e+00],
         [ 2.4519e-01,  2.0055e+00, -5.6868e-02,  7.5112e-01],
         [-1.8110e+00, -4.7682e-01,  8.0064e-01, -2.8683e-01]],

        [[ 2.3373e+00,  1.9925e+00,  1.8997e+00, -4.3554e+00],
         [-1.4728e-02, -1.3740e+00, -3.2872e-03,  2.2454e+00],
         [ 6.2883e-01,  1.4389e+00, -1.1982e+00, -1.2759e+00],
         [-3.3762e+00,  2.1935e+00, -5.9742e+00,  2.1481e-01],
         [-1.2529e+00, -5.8718e-01,  9.0496e-01,  3.6515e-02],
         [-1.2825e+00,  1.9573e-02, -4.4704e+00,  2.7455e+00]]])


In [116]:
x = torch.randn(1,23,12,12)
model = nn.ConvTranspose2d(23,23,4,4)
print(model(x).shape)

torch.Size([1, 23, 48, 48])


In [127]:
model = nn.Conv2d(in_channels=3,out_channels=3,kernel_size=3,padding=3,dilation=3)
x = torch.randn(1,3,48,48)
print(model(x).shape)

torch.Size([1, 3, 48, 48])


In [171]:
x = torch.randn(1,2,6,6)
y = x.permute(0,2,3,1)
#
z = rearrange(y, "b (j h) (i w) c -> b (j i) h w c", j=2, i=2)
print(z.shape)
z1 = rearrange(z, "b n hs ws c -> b n (hs ws) c")
print(z1.shape)

#print(torch.mean(z1,dim=2).shape)
print(z.max(4).values.shape)

torch.Size([1, 4, 3, 3, 2])
torch.Size([1, 4, 9, 2])
torch.Size([1, 4, 3, 3])


In [145]:
y.shape

torch.Size([1, 6, 6, 2])

In [146]:
print(z.shape)

torch.Size([1, 4, 3, 3, 2])


In [173]:
a = torch.randn(1,3,2)
b = torch.randn(1,3,2)
c = torch.stack([a,b],dim=1)
d = c.view(1, 2, -1, 2)
print(c.shape)
print(d.shape)

torch.Size([1, 2, 3, 2])
torch.Size([1, 2, 3, 2])


In [ ]:
def forward_corev1(self, x: torch.Tensor):
        self.selective_scan = selective_scan_fn_v1

        B, C, H, W = x.shape
        L = H * W
        K = 4

        x_hwwh = torch.stack([x.view(B, -1, L), torch.transpose(x, dim0=2, dim1=3).contiguous().view(B, -1, L)], dim=1).view(B, 2, -1, L)
        xs = torch.cat([x_hwwh, torch.flip(x_hwwh, dims=[-1])], dim=1) # (b, k, d, l)

        x_dbl = torch.einsum("b k d l, k c d -> b k c l", xs.view(B, K, -1, L), self.x_proj_weight)
        # x_dbl = x_dbl + self.x_proj_bias.view(1, K, -1, 1)
        dts, Bs, Cs = torch.split(x_dbl, [self.dt_rank, self.d_state, self.d_state], dim=2)
        dts = torch.einsum("b k r l, k d r -> b k d l", dts.view(B, K, -1, L), self.dt_projs_weight)
        # dts = dts + self.dt_projs_bias.view(1, K, -1, 1)

        xs = xs.view(B, -1, L) # (b, k * d, l)
        dts = dts.contiguous().view(B, -1, L) # (b, k * d, l)
        Bs = Bs.view(B, K, -1, L) # (b, k, d_state, l)
        Cs = Cs.view(B, K, -1, L) # (b, k, d_state, l)

        As = -torch.exp(self.A_logs.float()).view(-1, self.d_state)  # (k * d, d_state)
        Ds = self.Ds.view(-1) # (k * d)
        dt_projs_bias = self.dt_projs_bias.view(-1) # (k * d)

        # print(self.Ds.dtype, self.A_logs.dtype, self.dt_projs_bias.dtype, flush=True) # fp16, fp16, fp16

        out_y = self.selective_scan(
            xs, dts,
            As, Bs, Cs, Ds,
            delta_bias=dt_projs_bias,
            delta_softplus=True,
        ).view(B, K, -1, L)
        assert out_y.dtype == torch.float16

        inv_y = torch.flip(out_y[:, 2:4], dims=[-1]).view(B, 2, -1, L)
        wh_y = torch.transpose(out_y[:, 1].view(B, -1, W, H), dim0=2, dim1=3).contiguous().view(B, -1, L)
        invwh_y = torch.transpose(inv_y[:, 1].view(B, -1, W, H), dim0=2, dim1=3).contiguous().view(B, -1, L)
        y = out_y[:, 0].float() + inv_y[:, 0].float() + wh_y.float() + invwh_y.float()
        y = torch.transpose(y, dim0=1, dim1=2).contiguous().view(B, H, W, -1)
        y = self.out_norm(y).to(x.dtype)

        return y

In [ ]:
1

In [194]:
n_h=2
n_w=2
hs,ws = 2,2
topk=2
c=3
b=1

# (b, nh*nw, topk, hs*ws, v_C)
x = torch.randn(b,n_h*n_w, topk, hs*ws, c)
print(x)
# (b, nh*nw, hs*ws, topk*v_C)
y = x.transpose(2,3).reshape(b, n_h*n_w, hs*ws, -1)
y = rearrange(y, "b (n_h n_w) (hs ws) c -> b (n_h hs) (n_w ws) c", n_h=n_h,n_w=n_w, hs=hs,ws=ws)

tensor([[[[[ 1.5960, -0.2897,  1.1526],
           [ 0.4182, -1.0552, -0.2192],
           [ 1.3945,  1.0091, -0.0091],
           [ 1.1621, -1.1675, -0.1078]],

          [[ 0.6773, -0.5330, -1.9899],
           [ 0.2712,  1.7890,  1.6099],
           [ 0.7526,  0.2639, -0.3864],
           [-2.2052,  0.4431,  1.1777]]],


         [[[-0.4460,  0.9134, -1.3479],
           [ 0.4696, -0.2466,  0.7017],
           [-0.6725, -0.9298,  0.5703],
           [ 0.4514, -1.4434, -0.9434]],

          [[-0.4729,  1.3449, -1.4216],
           [-0.4286,  0.2768,  0.7340],
           [-0.1975, -0.0506,  0.3823],
           [ 0.3054, -0.8424,  0.1369]]],


         [[[-0.7593, -0.5113,  1.3651],
           [ 0.0711, -0.7994,  0.5936],
           [-0.0641,  1.5573, -0.8700],
           [ 0.0507,  0.1378,  0.3578]],

          [[-0.3581,  0.5776, -1.7871],
           [-0.6408, -2.1775,  0.0512],
           [ 0.4071, -1.1770, -1.0695],
           [-0.3540, -1.0241, -0.4422]]],


         [[[-0.5419,  

In [195]:
print(y)

tensor([[[[ 1.5960, -0.2897,  1.1526,  0.6773, -0.5330, -1.9899],
          [ 0.4182, -1.0552, -0.2192,  0.2712,  1.7890,  1.6099],
          [-0.4460,  0.9134, -1.3479, -0.4729,  1.3449, -1.4216],
          [ 0.4696, -0.2466,  0.7017, -0.4286,  0.2768,  0.7340]],

         [[ 1.3945,  1.0091, -0.0091,  0.7526,  0.2639, -0.3864],
          [ 1.1621, -1.1675, -0.1078, -2.2052,  0.4431,  1.1777],
          [-0.6725, -0.9298,  0.5703, -0.1975, -0.0506,  0.3823],
          [ 0.4514, -1.4434, -0.9434,  0.3054, -0.8424,  0.1369]],

         [[-0.7593, -0.5113,  1.3651, -0.3581,  0.5776, -1.7871],
          [ 0.0711, -0.7994,  0.5936, -0.6408, -2.1775,  0.0512],
          [-0.5419,  0.3260, -0.3682, -0.6299,  1.4888, -0.2925],
          [-0.6242,  0.3076,  1.4237, -0.2086, -0.5710, -0.2270]],

         [[-0.0641,  1.5573, -0.8700,  0.4071, -1.1770, -1.0695],
          [ 0.0507,  0.1378,  0.3578, -0.3540, -1.0241, -0.4422],
          [-0.8909, -0.3231,  0.5255, -0.6023,  1.7048,  1.3591],
    