In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange


In [47]:
x = torch.randn(1,3,6,6)
#print(x)
b,c,h,w = x.shape
n_w,n_h=2,2

y = F.unfold(x,kernel_size=(h//n_h, w//n_w),stride=(h//n_h, w//n_w))
y = y.transpose(1,2).reshape(1,n_w*n_h,c,(h*w)//(n_h*n_w)).transpose(2,3)
print(y.shape)
# z = rearrange(x, "n (j h) (i w) c -> n (j i) h w c", j=n_h, i=n_w)
# print(z.shape)

torch.Size([1, 4, 9, 3])


In [55]:
y

-0.28976666666666673

In [54]:
torch.mean(y,dim=2)

tensor([[[-0.2898, -0.1277, -0.1337],
         [-0.3539, -0.3940, -0.2608],
         [-0.4693, -0.2980,  0.2554],
         [ 0.3358,  0.0323,  0.2262]]])

In [56]:
y.mean(dim=2)

tensor([[[-0.2898, -0.1277, -0.1337],
         [-0.3539, -0.3940, -0.2608],
         [-0.4693, -0.2980,  0.2554],
         [ 0.3358,  0.0323,  0.2262]]])

In [67]:
a = torch.randn(1,6,6)
b = torch.randn(1,6,2,3)
print(a)
print(torch.topk(a,k=3,dim=2))
index = torch.topk(a,k=3,dim=2).indices

tensor([[[-0.5991,  0.7648, -0.5720,  2.0479, -1.6885,  0.1651],
         [ 0.6715,  0.8674, -1.2236,  0.0321,  1.2687, -1.7453],
         [ 0.4149,  1.0493,  1.3574, -1.3188, -0.9084, -0.9562],
         [ 1.5739,  0.4355,  1.2332,  0.6527,  0.0653, -2.0187],
         [ 2.2451, -0.4708,  1.0639, -1.2613,  0.9120,  1.8629],
         [-0.6142, -1.0106, -0.5500,  0.5309,  0.7194, -0.9959]]])
torch.return_types.topk(
values=tensor([[[ 2.0479,  0.7648,  0.1651],
         [ 1.2687,  0.8674,  0.6715],
         [ 1.3574,  1.0493,  0.4149],
         [ 1.5739,  1.2332,  0.6527],
         [ 2.2451,  1.8629,  1.0639],
         [ 0.7194,  0.5309, -0.5500]]]),
indices=tensor([[[3, 1, 5],
         [4, 1, 0],
         [2, 1, 0],
         [0, 2, 3],
         [0, 5, 2],
         [4, 3, 2]]]))


In [68]:
print(b) #(1,6,2,3)

tensor([[[[ 1.1312, -2.0286, -1.1819],
          [ 0.9590, -0.1457, -0.7932]],

         [[ 0.8317,  0.0247, -0.8975],
          [ 2.2067,  1.8521,  1.0173]],

         [[ 0.7001, -0.8354,  0.3814],
          [ 0.4911,  1.3858,  0.1873]],

         [[ 1.5381, -0.8013, -0.5527],
          [ 1.2489,  0.2170, -0.8703]],

         [[-0.2474, -0.4907,  0.0487],
          [-1.3639,  0.3985, -0.0991]],

         [[-2.2651,  0.0506, -0.0028],
          [-0.5266,  1.2990, -0.6306]]]])


In [71]:
inner_list = []
for i in index[0]:
    inner = b[:, i ,:,:].reshape(1,1,6,3)
    inner_list.append(inner)
print(torch.cat(inner_list,dim=1))


# c = b[:,[1,5,0],:,:].reshape(1,1,6,3)
# d = b[:,[0,1,4],:,:].reshape(1,1,6,3)
# out = torch.cat([c,d],dim=1)
# print(out)
# print(c.shape)

tensor([[[[ 1.5381, -0.8013, -0.5527],
          [ 1.2489,  0.2170, -0.8703],
          [ 0.8317,  0.0247, -0.8975],
          [ 2.2067,  1.8521,  1.0173],
          [-2.2651,  0.0506, -0.0028],
          [-0.5266,  1.2990, -0.6306]],

         [[-0.2474, -0.4907,  0.0487],
          [-1.3639,  0.3985, -0.0991],
          [ 0.8317,  0.0247, -0.8975],
          [ 2.2067,  1.8521,  1.0173],
          [ 1.1312, -2.0286, -1.1819],
          [ 0.9590, -0.1457, -0.7932]],

         [[ 0.7001, -0.8354,  0.3814],
          [ 0.4911,  1.3858,  0.1873],
          [ 0.8317,  0.0247, -0.8975],
          [ 2.2067,  1.8521,  1.0173],
          [ 1.1312, -2.0286, -1.1819],
          [ 0.9590, -0.1457, -0.7932]],

         [[ 1.1312, -2.0286, -1.1819],
          [ 0.9590, -0.1457, -0.7932],
          [ 0.7001, -0.8354,  0.3814],
          [ 0.4911,  1.3858,  0.1873],
          [ 1.5381, -0.8013, -0.5527],
          [ 1.2489,  0.2170, -0.8703]],

         [[ 1.1312, -2.0286, -1.1819],
          [ 0.959

In [64]:
c.reshape(1,1,6,3)

tensor([[[[ 0.9395,  1.0641,  0.3440],
          [ 0.3677,  0.2351, -1.2597],
          [ 0.3056,  0.0020,  0.2651],
          [-0.0344, -1.7146,  1.1489],
          [-1.3257,  1.2709, -0.3341],
          [-1.2552, -0.2155,  1.1634]]]])

In [73]:
a = torch.randn(2,3,4)
for i in a[:,]:
    print(i)

tensor([[-0.1287, -1.0688,  0.9372,  0.0701],
        [ 0.6310, -0.4409,  0.9477, -1.9170],
        [-1.5138,  0.7465, -0.4902,  1.5684]])
tensor([[ 0.1882, -0.5668,  0.8773,  0.4107],
        [-0.6995, -1.0611, -0.2847,  0.8241],
        [-0.6709,  2.2328, -1.3086,  1.0862]])


In [106]:
x = torch.randn(2,4,3,2)
x_c = x.reshape(2,4,6)
#weight = torch.randn(2,4,4)
weight = torch.tensor([[[1,1,1,1],
                        [2,2,2,2],
                        [3,3,3,3],
                        [4,4,4,4]],
                        [[1,1,1,1],
                        [2,2,2,2],
                        [3,3,3,3],
                        [4,4,4,4]]]).float()
y = (weight @ x_c).reshape(2,4,3,2)
print(y.shape)


torch.Size([2, 4, 3, 2])


In [110]:
print(x)
print((-0.5664-1.7262-1.9974+0.5379))

tensor([[[[-0.5664, -0.2502],
          [-2.0445,  0.9714],
          [-0.8704,  0.5467]],

         [[-1.7262, -0.8312],
          [-0.3956, -0.7278],
          [ 1.2235,  0.7945]],

         [[-1.9974, -0.1119],
          [ 0.1305,  2.2807],
          [-0.1256,  0.5401]],

         [[ 0.5379,  2.1022],
          [ 0.7766, -0.5122],
          [-0.9301, -0.7955]]],


        [[[-0.3646, -2.4609],
          [ 1.7166,  0.4990],
          [-1.0074,  0.0069]],

         [[-1.2731, -0.5790],
          [-0.0949, -0.3038],
          [ 1.8223, -0.3854]],

         [[-0.6517, -0.4266],
          [ 1.7285,  0.8174],
          [-0.4383,  0.2333]],

         [[ 0.3802, -0.1078],
          [ 1.3541, -1.7146],
          [ 1.3281,  0.0764]]]])
-3.7521


In [108]:
print(y)

tensor([[[[ -3.7520,   0.9089],
          [ -1.5330,   2.0121],
          [ -0.7025,   1.0858]],

         [[ -7.5041,   1.8177],
          [ -3.0660,   4.0243],
          [ -1.4051,   2.1716]],

         [[-11.2561,   2.7266],
          [ -4.5990,   6.0364],
          [ -2.1076,   3.2574]],

         [[-15.0082,   3.6354],
          [ -6.1320,   8.0485],
          [ -2.8101,   4.3432]]],


        [[[ -1.9092,  -3.5742],
          [  4.7042,  -0.7019],
          [  1.7047,  -0.0687]],

         [[ -3.8185,  -7.1485],
          [  9.4085,  -1.4039],
          [  3.4094,  -0.1374]],

         [[ -5.7277, -10.7227],
          [ 14.1127,  -2.1058],
          [  5.1141,  -0.2061]],

         [[ -7.6369, -14.2970],
          [ 18.8169,  -2.8077],
          [  6.8188,  -0.2748]]]])


In [103]:
a = torch.randn(2, 6, 4)
b = torch.randn(2, 4, 4)
print(torch.matmul(a, b))  # 进行张量乘法

tensor([[[ 6.2814e-01,  3.5876e-02, -5.6434e-01,  1.1323e+00],
         [-1.4727e+00, -2.5746e-01,  6.5216e-01, -1.2715e+00],
         [ 1.9681e+00,  5.7480e+00, -3.5879e-01, -1.2408e+00],
         [-1.4625e+00, -1.2430e+00,  1.1019e+00,  3.9845e+00],
         [ 2.4519e-01,  2.0055e+00, -5.6868e-02,  7.5112e-01],
         [-1.8110e+00, -4.7682e-01,  8.0064e-01, -2.8683e-01]],

        [[ 2.3373e+00,  1.9925e+00,  1.8997e+00, -4.3554e+00],
         [-1.4728e-02, -1.3740e+00, -3.2872e-03,  2.2454e+00],
         [ 6.2883e-01,  1.4389e+00, -1.1982e+00, -1.2759e+00],
         [-3.3762e+00,  2.1935e+00, -5.9742e+00,  2.1481e-01],
         [-1.2529e+00, -5.8718e-01,  9.0496e-01,  3.6515e-02],
         [-1.2825e+00,  1.9573e-02, -4.4704e+00,  2.7455e+00]]])
